### ISSUE TITLE
https://scalapb.github.io/grpc.html has a breaking link

### ISSUE THREAD

**Issue by jyane** [xuwei-k/grpc-scala-sample#10]
`https://scalapb.github.io/grpc.html` links to `https://github.com/xuwei-k/grpc-scala-sample/tree/master/grpc-scala/src/main/scala/io/grpc/examples/routeguide`
but it doesn't exist. I think it is not implemented yet?

So, making an issue to scalapb team or implementing a route guide example is better for scala(pb) beginners.

**Comment by xuwei-k** [comment]
I have implemented in https://github.com/xuwei-k/grpc-scala-sample/commit/72ea92c7ea01970e1c9950509faef99d2f8809cf#diff-b84192598b743a50efed71ff3b1b92aa

But removed in https://github.com/xuwei-k/grpc-scala-sample/commit/4c4374605088dde8fb8c42772adf00fccd9cd5d5 because these example outdated.
We should re-implement these examples.

**Comment by xuwei-k** [comment]
https://github.com/scalapb/ScalaPB/commit/0800c3c846cec80417ab3e4112650c74618be910
